name: BloodpressureTracker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Specify your .NET version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build the project
        run: dotnet build --no-restore

      # Step 5: Migrate Database
      - name: Fix permissions for Data_and_Models
        run: chmod -R 755 ./Data_and_Models

      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef
        env:
          DOTNET_ROOT: /usr/share/dotnet

      - name: Run database migrations
        working-directory: ./Data_and_Models
        run: dotnet ef database update

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/measurementservice:latest -f MeasurementService/Dockerfile .
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/patientservice:latest -f PatientService/Dockerfile .
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bptmigration:latest -f Data_and_Models/Migration.Dockerfile .

      # Step 8: Push the Docker images to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/measurementservice:latest
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/patientservice:latest
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bptmigration:latest
      
